### ISSUE TITLE
to mapbox or not

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-directions.js#1]
Should it depend on mapbox.js? Should it be namespaced as `L.mapbox.directions`?

**Comment by jfirebaugh** [comment]
Leaning towards mapbox-directions.js, `L.mapbox.directions`, and a `mapbox-directions` namespace for CSS classes.

**Comment by mourner** [comment]
I think it should. mapbox.js is our integration layer, and the directions plugin belongs to that. People who use Mapbox directions will probably use other Mapbox services as well. If it's lean enough, I'd even consider merging it into mapbox.js repo.

**Comment by jfirebaugh** [comment]
Renamed.
