### ISSUE TITLE
impressions from Tristen

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-directions.js#10]
![image](https://f.cloud.github.com/assets/98601/1903164/619fde6e-7c7d-11e3-9295-a06c1d9cf690.png)

**Comment by tristen** [comment]
Ah thanks - that post wasn't the place for this. I should have said there isn't any implied action to route after input. There could just be a little hand holding.

**Comment by jfirebaugh** [comment]
Split into #16 and #17.
