### ISSUE TITLE
Mapbox directions API profile not working correctly

### ISSUE THREAD

**Issue by bryandh** [mapbox/mapbox-directions.js#106]
When I call the Mapbox Directions API for driving directions between two coordinates, it returns data for the cycling profile instead of the driving profile. When calling the API for cycling directions, it returns data for the driving profile instead of the cycling profile.

Only the walking profile seems to work correctly.

The API used to return the correct dataset before. I noticed the change when the duration was very off from what the API used to return.

Example URL for driving
https://api.mapbox.com/directions/v5/mapbox/driving/4.334225,51.572969;3.872782,51.486525.json?steps=true&overview=full&geometries=geojson&access_token=[ACCESTOKEN]

Example URL for cycling
https://api.mapbox.com/directions/v5/mapbox/cycling/4.334225,51.572969;3.872782,51.486525.json?steps=true&overview=full&geometries=geojson&access_token=[ACCESTOKEN]

Screenshot when calling the API with the cycling profile but getting driving profile data back.
![screenshot 2016-08-22 12 23 41](https://cloud.githubusercontent.com/assets/11500592/17851643/48c2182e-6863-11e6-96a1-58b4869cb8b1.png)

Screenshot when calling the API with the driving profile but getting cycling profile data back.
![screenshot 2016-08-22 12 28 08](https://cloud.githubusercontent.com/assets/11500592/17851739/ead266a0-6863-11e6-9efc-cadd38701c39.png)

**Comment by freenerd** [comment]
Thanks for reporting. We are seeing the same issue and investigate it right now.

**Comment by freenerd** [comment]
We have found the issue and resolved it. It was a misconfiguration on our side. Can you check again if it works as expected now?

**Comment by bryandh** [comment]
It works exactly as expected now.
Thank you very much for the quick response and fix!
