### ISSUE TITLE
router issue?

### ISSUE THREAD

**Issue by wyattp11** [mapbox/mapbox-directions.js#108]
When I query Monterey, CA to Sacramento, CA I am getting some anomalies...

1) Directions will return only one route sometimes, then two routes. It will also prioritize them differently. Are current traffic conditions influencing what route is returned and how many?

2) I am getting directions to roads off highway in driving mode. See screen grab:
![routererror](https://cloud.githubusercontent.com/assets/13744093/19549968/f96f6908-965b-11e6-92e8-377f8ed69e85.jpg)

I just replicated this in the Mapbox GL directions as well, so I assume this is the underlying routing engine with the error and not directions.js... sorry wasn't sure where to post this?

**Comment by niborg** [comment]
I'm similarly having a problem with the directions API router not recognizing paths in OpenStreetMap.  E.g., when using the [mapbox sample directions page](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/), I'm unable to plot a walking path between A and the trail in the middle of the picture:

![screenshot from 2016-10-21 20-55-52](https://cloud.githubusercontent.com/assets/11550412/19616803/d15bbe40-97d1-11e6-9424-16ee337ef622.png)

You can access the route data [here](https://www.openstreetmap.org/edit?editor=id#map=17/29.62362/-99.20697) on OSM if you log in (I think).

**Comment by wyattp11** [comment]
Just checked OSRM, same error and Mapbox based. Graphopper and LRM route properly (on highway) so appears to be Mapbox router error.

**Comment by wyattp11** [comment]
Also just tried to manipulate the route manually using readonly: false and the router refuses to use these sections of the highway... seems like a map data issue, happens on streets, light and dark styles.

**Comment by danpat** [comment]
@wyattp11 Sorry for the slow response - this is definitely a problem on our end when finding the route.  It looks like there are some HOV lane designations that we're incorrectly interpreting on I-80 that is forcing the route off the main road.  HOV lane handling is new, so this is likely a bug.

We're workin' on a fix, will update this ticket when solved.

**Comment by wyattp11** [comment]
@danpat awesome thanks, @lyzidiamond just sent the link to the directions feedback on Mapbox but it only provides the one route down I-5 so I can't submit the I-80 route there.

**Comment by danpat** [comment]
@wyattp11 We deployed a fix for this yesterday, and now that the map has been re-processed, the routes are looking much better:

<img width="497" alt="screen shot 2016-10-26 at 8 05 52 am" src="https://cloud.githubusercontent.com/assets/1892250/19729110/146a01ea-9b53-11e6-9b11-7d6678119ec9.png">

Thanks for the report, and sorry it took so long to get it fixed!

**Comment by wyattp11** [comment]
Awesome, thank you. Working on my end!
