### ISSUE TITLE
Directions does not recognize valid paths

### ISSUE THREAD

**Issue by niborg** [mapbox/mapbox-directions.js#109]
I'm having a problem with the directions API router not recognizing paths in OpenStreetMap.  E.g., when using the [mapbox sample directions page](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/), I'm unable to plot a walking path between A and the trail in the middle of the picture:

![screenshot from 2016-10-21 20-55-52](https://cloud.githubusercontent.com/assets/11550412/19616803/d15bbe40-97d1-11e6-9424-16ee337ef622.png)

You can access the route data [here](https://www.openstreetmap.org/edit?editor=id#map=17/29.62362/-99.20697) on OSM if you log in (I think).

**Comment by niborg** [comment]
I've played around with creating and modifying paths elsewhere, with and cannot recreate this specific issue.  Only distinction I can draw with respect to the above scenario is that the starting location is designated as a 'bridle path' and the (desired) ending location is designated as a 'foot path' (both paths are designated as permissible to both pedestrians and bikes).  Any ideas?

**Comment by daniel-j-h** [comment]
The [way in question](https://www.openstreetmap.org/way/32713960#map=19/29.62293/-99.20729&layers=D) seems to be a [bridleway](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dbridleway) with explicit `bicycle=yes` and `foot=yes` tags.

You are right, this should be routed over

**Comment by daniel-j-h** [comment]
I'm closing this ticket in favor of https://github.com/Project-OSRM/osrm-backend/issues/3335 upstream with the routing engine.

Thanks for reporting - we're working on fixing this!
