### ISSUE TITLE
Simple routing example needed

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-directions.js#114]
Sorry in advance,

well I think I have a rather simple question, but don't know how to connect the dots.
I want to implement a simple map, with a simple route from A to B and that's it. So that people who are using my page can play around with the map. Nothing fancy, I think...

So I found in the docs, how a api-call should look like:
`https://api.mapbox.com/directions/v5/mapbox/driving/167.7180,-45.4146;168.7278,-44.9682?access_token=MY_KEY`

And when I paste it into my browser it seems like it's working perfectly. So far so good, but how can I implement now the JSON-result into my page? 

Every bit of help is apreciated!

**Comment by danpat** [comment]
@bastoGrande You need some code to take the JSON response and draw it on a map.  That's exactly what this repository `mapbox-directions.js` does.

Take a look at the example HTML page in the root directory:

https://github.com/mapbox/mapbox-directions.js/blob/mb-pages/index.html

It shows how to use `mapbox-directions.js` to draw a map, request a route and draw it on a map.  It includes a geocoder component so you can do an address search, and you can drag the markers around on the map to change the route manually.

**Comment by ghost** [comment]
Sorry, but that example is already too much for me. I can't figure it out what part I need. 

Like I said, I just want a fixed route rendered. I don't need any Input or other stuff to play.

I guess the part that interests me is this one:
```
directions
                .setOrigin(toLatLng(waypoints[0]))  

                .setDestination(toLatLng(waypoints[waypoints.length - 1]))  

                .setWaypoints(waypoints.slice(1, waypoints.length - 1).map(toLatLng))  

                .query();
```
Is there a way that I can just load this part at the load event of the page? I have no clue how javascript works.

**Comment by danpat** [comment]
@bastoGrande One important thing you haven't mentioned: are you using a raster or vector map 
 How you draw the route line differs depending on which mapping component you're using.

All of `mapbox.js` (raster), `leaflet.js` (raster) and `mapbox-gl.js` (vector) support adding GeoJSON layers.

If you add `&overview=full` to the Directions API URL that you call, part of the response will be a GeoJSON geometry object that you can add to your map component.

Unfortunately, without a lot more details, I can't be more specific than that.  If you're using Leaflet or `mapbox.js`, look at the documentation and examples for how to add a GeoJSON layer.  You can extract the GeoJSON object from the Directions API response and it should be just a single function call to add it to the map.

**Comment by ghost** [comment]
Ok, like I said I'm sorry to ask such a basic thing.
I'll try to describe my problem:

I have a jekyll-blog set up, where I want to show a map with a route from A to B in a blog-post. No User-Input, just a simple map with some scrolling and movement of the map. 
After some research I landed at mapbox. I still think it might be like to "take a sledgehammer to crack a nut", but couldn't find something more basic.

I think I don't need `leaflet.js` and don't want to use `mapbox-gl.js`. So guess I need raster maps.
The request in my original question isn't anywhere implemented or neither needed. It was just something I got to work and thought I could implement it somewhere easy and without a big implemention.

I thinkt I would need something like this: 
```
<script>
L.mapbox.accessToken = 'pk....';
L.mapbox.map('map', 'mapbox.streets').setView([-45.4146, 167.7180], 9);

//getting somehow the directions into the map rendered..

</script>
```

**Comment by danpat** [comment]
@bastoGrande If you want the map to move/zoom, then you'll need to use a "slippy map framework" - this includes Leaflet, Mapbox GL JS, OpenLayers, etc.  Sorry, you've entered a world of complexity, there's no way around it.  If you don't want the map to move, you could always just take a screenshot and insert a static image, but if you want a zoomable map, things get more complicated, quickly.

Here's a short blogpost that describes how to use LeafletJS along with Mapbox map tiles to display a zoomable map in your blog:

http://jgardiner.co.uk/blog/a-basic-leaflet-map-in-jekyll

Once you've got that working, you can add the following code after the last line of code in the example.  The code below will fetch your route from the Mapbox Directions API, extract the geometry from it (the longitude/latitude coordinates for the routeline), convert them to a form for Leaflet, then add the line in red on the map.  Note that I haven't tested this code, you may need to do a little debugging to get it to work like you want it.

```
function loadJSON(path, success, error)
{
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function()
    {
        if (xhr.readyState === XMLHttpRequest.DONE) {
            if (xhr.status === 200) {
                if (success)
                    success(JSON.parse(xhr.responseText));
            } else {
                if (error)
                    error(xhr);
            }
        }
    };
    xhr.open("GET", path, true);
    xhr.send();
}

// Note the addition of the "overview=full&geometries=geojson" parameters - these simplify extracting the actual line from the response quite a bit.
var URL ='https://api.mapbox.com/directions/v5/mapbox/driving/167.7180,-45.4146;168.7278,-44.9682?overview=full&geometries=geojson&access_token=YOUR_KEY';

loadJSON(URL,
  function(jsonobject) {
    var coordinates = jsonobject.routes[0].geometry.coordinates;
    // The API response is GeoJSON which has coordinates in lon/lat order - Leaflet needs lat/lon, so we need to swap them all
    coordinates = coordinates.map(c => [c[1],c[0]]);
    var polyline = L.polyline(coordinates, {color: 'red'}).addTo(map);
    map.fitBounds(polyline.getBounds());
  },
  function(error) {
    console.log(error);
  }
}
```

**Comment by ghost** [comment]
Thank you so much! 
With your example I did understand what I need to do and even could do some personal adjustments. 

I just have one last question. Now there are two `<hr>`-tags in front of my map in the final html and I have no clue how they get there. It's likely the leaflet.js or .css, isn't it?

**Comment by danpat** [comment]
@bastoGrande your guess is as good as mine, but I don't think the `<hr>` comes from Leaflet.

**Comment by ghost** [comment]
Well, then I'll close this issue for now. 

Thank you again!
