### ISSUE TITLE
mapbox bearing and real compass bearings don't match

### ISSUE THREAD

**Issue by adarsh9975** [mapbox/mapbox-directions.js#117]
I am using the directions API from Mapbox. I was verifying whether the data in "bearing-after" tag and the actual bearing returned in json response are same or not.  Actual bearing was measured using a digital compass while facing the desired bearing at the coordinates of maneuver .I came to know that these two readings were drastically different. I verified it using other compass too.

while searching on internet I came to know about the "bearing" and "radius" options that are passed to url during request process, and something about the returned bearings being affected by these parameters, but I don't get what it means (read documentations too, still unclear).

**Can someone tell me why the bearings returned by Mapbox-directions-API and actual compass bearings don't match and how to correct this.**

P.S: Declination in my area is just 0.26 but the readings are off by 30-40 degrees. The digital compass has been compensated for its offset too, so it's not equipment fault for sure.

**Comment by danpat** [comment]
@adarsh9975 Can you post a specific example?

**Comment by adarsh9975** [comment]
@danpat 
![screenshot_1](https://user-images.githubusercontent.com/31591230/38044540-bd2cc4c6-32d7-11e8-8452-680f3713163f.png)

I played around with this a bit. Referring to the image. The marked point is the only point-of-maneuver. The "bearing-after" that i get here is 66 degrees. But since this is a **u-turn** and the destination is towards 188 degrees, i was expecting it to return 188 in the bearing-after tag. 

I suspect that this is due to the route not being broken down into enough steps rather than bearing not being correct? I could try making way-points around the u-turn, but this won't solve the problem in the long run, since i can't plot way-points every time a new route is desired. 

Is my suspicion correct ?

**Comment by danpat** [comment]
@adarsh9975 Can you provide the specific coordinates for this example?  To fully answer your question, I probably need to check the actual geometry here.

**Comment by adarsh9975** [comment]
Start: 18.653145, 73.762467
Stop: 18.652855, 73.762560
 
these are the only 2 coordinates that i'm feeding into the request url.

**Comment by danpat** [comment]
@adarsh9975 So, here's the route you're using:

https://www.mapbox.com/get-directions/#17.31/18.65297/73.76245?coordinates=73.76235641367089,18.653104862582552;73.76254638673458,18.652834183943412

The Mapbox Directions API here is reporting a "turn right", not a "u-turn".  Also note that the shape of the road on the Mapbox map is quite different to your screenshot - is your screenshot from Google?  I think I recognize the styling there.

The directions that the Mapbox Directions API returns are based on the geometry/shape of the Mapbox map (based on OpenStreetMap, not Google), and at this location, the angles are different to what Google is showing.

The bearings being returned in the API response *do* match the shape of the roads as currently drawn in OpenStreetMap.

If you think the shape of the road is wrong here, you might want to consider updating OpenStreetMap here: https://www.openstreetmap.org/edit#map=19/18.65312/73.76244

Based on the satellite imagery background, I agree that the road geometry doesn't really match reality very well here.  It may take a few days for edits to OpenStreetMap to propagate out to the Mapbox Directions API.

**Comment by adarsh9975** [comment]
Okay, I have edited this road and submitted it for review. hopefully the update happens fast. Thank you for your help Daniel 👍
