### ISSUE TITLE
use start/end icons on markers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-directions.js#15]

**Comment by jfirebaugh** [comment]
@samanpwbb What do you think about putting all the maneuver icons into maki?

**Comment by samanpwbb** [comment]
I'm not sure all the maneuver icons make sense in maki. As soon as I add them, they'd become available through the API and in the online editor. It feels a bit weird to have all these direction icons side by side with what so far has been exclusively POI icons.

I would rather: 
- Add left/right/up/down directional arrow icons to maki 
- Use the up arrow maki icon for start
- Use the star maki icon for finish
- Replace the start icon in Mapbox directions with an up arrow (that matches maki), and the finish icon in Mapbox direction with a star

How does this sound? I can hit this stuff on Monday

**Comment by jfirebaugh** [comment]
Yeah, sounds good.

**Comment by samanpwbb** [comment]
After going in a few circles, I find 'A' and 'B' symbolism to be clearest and easiest to understand.
