### ISSUE TITLE
open source this

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-directions.js#19]
- [x] V4 API launched
- [x] Design pass
- [x] API docs
- [x] License
- [x] Where should the public version of https://hey.mapbox.com/mapbox-directions.js/ live?

/cc @tmcw @lxbarth for opinions on the last item.

**Comment by mourner** [comment]
Re last item, what about integrating it into the Mapbox editor? Routes are a natural thing to share for users, and it would be awesome to make it easy to get directions and share results through the Mapbox share workflow.

This way we could also avoid making yet another entry point for showcasing Mapbox services. One map interface to rule them all is better IMO.

**Comment by samanpwbb** [comment]
@mourner for background on editor+routing see https://github.com/mapbox/mapbox.github.com/issues/2936

**Comment by jfirebaugh** [comment]
Right, https://hey.mapbox.com/mapbox-directions.js/ is for serving as the canonical example code for directions, not as a consumer service.

**Comment by mourner** [comment]
Wow, don't know how I missed that ticket — thanks!

**Comment by tmcw** [comment]
@jfirebaugh are these the only tasks for launching this? I was under the assumption that we were waiting for directions to be out of beta - if that's not a blocker, I'd love to just hit these tomorrow and hit the button.

**Comment by jfirebaugh** [comment]
I'm inclined to wait for v4 API / metered access, but no strong feelings either way.

**Comment by tmcw** [comment]
Same. Adding that to the checklist.

**Comment by tmcw** [comment]
v4 is launched, license is included, [docs need to be written](c1c4077ee321a4397ea210b2fba8c9ce1bf6f051)

**Comment by tmcw** [comment]
> Where should the public version of https://hey.mapbox.com/mapbox-directions.js/ live?

As a mapbox.js example.

**Comment by tmcw** [comment]
@jfirebaugh just pushed a v4 update, as long as [the way i use access tokens](https://github.com/mapbox/mapbox-directions.js/commit/4208231ce14c80230f657d59d2760690d78ed146#diff-030dc034143435907e8abd6287b18045R95) looks good to you, it's good to go, and I'd love to open this, push it to the plugin cdn, and make an example pronto.

**Comment by jfirebaugh** [comment]
Adjusted slightly in 8a37f7bb643a8b7476c50d458ca4a9cc22b097ac.

:+1: do it!

**Comment by tmcw** [comment]
Cool!
