### ISSUE TITLE
Redesign the directions demo

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-directions.js#20]
Goal: make the directions demo help developers and designers imagine what is possible. It should look and behave more like the kind of thing we'd like to see clients building with the API, rather than like a standalone site.

Consider making it easy to turn components of the UI on or off, or at least suggest that this would be possible by designing something really light. 

Remove branding, make the design more neutral. Less UI more map.

~~Will post sketches before diving into code.~~

**Comment by jfirebaugh** [comment]
:+1: Interested to see what you come up with.

**Comment by samanpwbb** [comment]
Happening in `redesign` branch.

@jfirebaugh would love for you to take a look and provide feedback if you have some time tomorrow. There are a also a couple tickets that I could use your help with (mostly, https://github.com/mapbox/mapbox-directions.js/issues/21 / https://github.com/mapbox/mapbox-directions.js/issues/23 )

**Comment by gundersen** [comment]
@samanpwbb want to post some screenshots of the progress you are making? Also any chance in having a staging up so we can be playing? aka I love demoing :)

**Comment by samanpwbb** [comment]
@gundersen looks like this:

![png-1](https://f.cloud.github.com/assets/108094/2020345/4db0af4a-8831-11e3-9051-45ff457246cb.png)
![png](https://f.cloud.github.com/assets/108094/2020306/f176a70c-8830-11e3-80f9-afbc5bfdcf6e.png)

Will get a staging branch up soon.

**Comment by DennisOSRM** [comment]
The UI is nice. Will it also feature a map that is more suitable for routing?

**Comment by samanpwbb** [comment]
@DennisOSRM I am just using Mapbox Streets for now. We don't currently have a general purpose routing map. I'll bring this up with @ajashton and see if we can put something more suitable together.

**Comment by jfirebaugh** [comment]
@samanpwbb Nice clean design with a lot of map. My concerns:
- Still hard to infer what reverse icon does. The icon is just kind of hanging out in space. I think there was an intermediate design where it was between "Start" and "End" and I liked that.
- Don't use the same icon for waypoints (dragged route) and maneuver indicator when hovering a step. Need to be able to tell those apart.
- Not clear to me how you intend the clear interaction to work (#23).

**Comment by samanpwbb** [comment]
@jfirebaugh hit the first two of your three points, submitted a PR: https://github.com/mapbox/mapbox-directions.js/pull/28

**Comment by gundersen** [comment]
HUGE improvement @samanpwbb
