### ISSUE TITLE
Make close buttons properly clear route  & hide results

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-directions.js#23]
Needs to be done right.

**Comment by jfirebaugh** [comment]
I'm not sure about having two separate buttons. What exactly is each one supposed to do? As a user, I really just want one button that clears everything.

**Comment by samanpwbb** [comment]
I ended up with this approach because I wanted to be able to keep my start or end point and then just click the map to place whichever marker I had reset again, rather than being required to drag the marker to move one of the points. 

It also helps a user reset search after getting an error. Right now the error state is confusing and difficult to escape.

The alternative approach I see would require these two interactions:
- Click a button inside the drawer that clears everything
- Click a button to clear errored input in error message dialog, or automatically clear errored input when triggered.

**Comment by jfirebaugh** [comment]
So clicking one of the input buttons should remove the corresponding marker from the map, remove the current route and any intermediate waypoints, remove any errors, and reset the permalink? Let me implement that and see how it feels.

**Comment by samanpwbb** [comment]
@jfirebaugh yes this was what I had in mind – if it feels awkward lets try something else.
