### ISSUE TITLE
Convert encoded characters in place names

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-directions.js#25]
![screen shot 2014-01-28 at 1 36 18 am](https://f.cloud.github.com/assets/108094/2016775/a249f674-87e6-11e3-8862-3c6f4de123e2.png)

**Comment by jfirebaugh** [comment]
Can you link the route that shows this?

**Comment by samanpwbb** [comment]
Here's an example: http://localhost:8000/?route=-122.3983,37.7997;-122.4425,37.7398#14/-122.4207/37.7463

**Comment by jfirebaugh** [comment]
Looks like the entity encoding is present in the response lean JSON from OSRM. @DennisOSRM this seems like a bug -- JSON strings such as `route_summary.start_point` and `route_name` should not be entity encoded.

**Comment by DennisOSRM** [comment]
The encodings were added to guard against JSON/HTML/... injections by way name.

**Comment by jfirebaugh** [comment]
Escaping the text for a particular output format is the responsibility of the client. The web service is a general purpose API and should not enforce HTML encoding. For now I will un-encode the text in mapbox-osrm-transform, but this should be fixed upstream.

**Comment by DennisOSRM** [comment]
True, HTML encodings were a hack. What's the JSON way of escaping strings?

**Comment by jfirebaugh** [comment]
The only characters that must be escaped in JSON strings are `"`, `\`, and control codes less than U+0020. (And if you're sending JSONP, [U+2028 and U+2029](http://timelessrepo.com/json-isnt-a-javascript-subset).)

**Comment by DennisOSRM** [comment]
Tracking in https://github.com/DennisOSRM/Project-OSRM/issues/895

**Comment by jfirebaugh** [comment]
Closing, will be fixed on the backend.

**Comment by DennisOSRM** [comment]
This is implemented now and will be pushed to develop branch shortly
