### ISSUE TITLE
Improving routing interaction

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-directions.js#26]
Not sure how much we want to nail this UI, but here are a few steps that would go a long way:
- Add a bar of helper text below inputs: 
  Default text: `Click map or enter a location above to start your route.`
  
  If 'Start' has content: `Click map or enter location to finish your route`
  
  Once a route has been finished, display: `Click and drag anywhere on your route to add intermediate steps`. 
  
  Use the same space for error reporting.

~~\- By default, show only a single input field. Once user has focused it, reveal second field.~~

~~\- Add a routing popup to the map that functions like our 'place marker' popup in the mapbox editor. Creates a new starting point if no route exists, new ending point if starting point exists, and overrides end point with new end point if end point exists.~~
- Allow user to drag start and end inputs to re-order them.

~~\- Display intermediate steps as inputs between start and end points.~~

**Comment by gundersen** [comment]
Like the idea of  dragging intermediate steps, start and end points but don't let that be a distraction. That level of detail is rarely needed when driving right? Cool as something that would not work, but I would not let people know it works unless people see it works - aka no need to make this obvi, it is something that can happen when people try to more a marker or something or the line, but other wise is just an easter egg. In short people want to start, end, see rout options, see turn by turn.

**Comment by jfirebaugh** [comment]
I've seen the non-standard "click to set origin/destination" interaction confuse people (especially since it doesn't support search). Dragging markers and the route seems pretty familiar to most people.

**Comment by samanpwbb** [comment]
Crossed out the bad ideas on this list :+1:

**Comment by samanpwbb** [comment]
Actually going to just close this - we don't need hints. Demo feels a lot tighter now so no need.
