### ISSUE TITLE
Use lat/lng if no valid place name in input field

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-directions.js#27]
What's happening here: http://localhost:8000/?route=-101.382,40.246;-86.704,47.547#8/-87.759/47.305

No error, I get a legitimate route, but the destination input is not filled: 
![screen shot 2014-01-28 at 12 05 06 pm](https://f.cloud.github.com/assets/108094/2021378/65ca93c2-883e-11e3-9f58-f9f9ac1c23cb.png)

Looks like if there's not a name for the point, input is empty when it should be a lat/lng

**Comment by jfirebaugh** [comment]
Fixed in 19969a97119cb599bf09163b7285fad072b96930.
