### ISSUE TITLE
Duration times see very low

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-directions.js#36]
Try comparing a few route.

cc @DennisOSRM

**Comment by DennisOSRM** [comment]
Durations are overly optimistic. What are the  durations in question here?

**Comment by bsudekum** [comment]
@DennisOSRM the times seem extremely underestimated

**Comment by DennisOSRM** [comment]
@rsudekum can you provide links to Google where you think it is especially off?

**Comment by gundersen** [comment]
y, I almost want to just run up the numbers buy like +3mn, to make sure short distances look a little longer. Is that dirty?

**Comment by DennisOSRM** [comment]
Multiply the duration by 1.3. that should give a better estimate. I'll review the default speed estimates tomorrow, too.

**Comment by gundersen** [comment]
love it @DennisOSRM.

**Comment by bsudekum** [comment]
> Multiply the duration by 1.3.
> :thumbsup:

**Comment by DennisOSRM** [comment]
Some further investigation shows that urban traffic durations are overestimated while arterial traffic is mostly fine. I will make a couple of adjustments to the urban traffic speeds.

**Comment by DennisOSRM** [comment]
Ok, got a good lead on this. While not yet perfect, the duration estimates will be fixed upstream.

**Comment by DennisOSRM** [comment]
This is now implemented upstream: https://github.com/DennisOSRM/Project-OSRM/commit/d73f3ebd1bde36c2e5b41edb44a703cfb09cd7a0

**Comment by bsudekum** [comment]
@DennisOSRM great, want to give me a heads up when this is merged into mapbox-directions?

**Comment by DennisOSRM** [comment]
@rsudekum sure. We would need to pin a newer version and to reprocess data files. I am happy to upload the latter from my daily updates. 

Cc: @willwhite

**Comment by springmeyer** [comment]
The Project-OSRM pin is in the node-osrm Travis.yml. Bump that and then see the releasing steps in the node-osrm README.

**Comment by DennisOSRM** [comment]
@springmeyer thanks for the info.

Update: Done with https://github.com/DennisOSRM/node-osrm/commit/bc155ffaa7aa6bef0cb355f14ae451b139fb03f6

**Comment by willwhite** [comment]
Awesome. @DennisOSRM did you also push a new release for the module?

I an writing up steps for deploying new data. If you kick off the data processing job I should have a destination setup on S3 by the time it is done.

**Comment by DennisOSRM** [comment]
@willwhite Didn't push a new release for the module yet. I can push preprocessed data over ssh/scp from my demo server tomorrow. preprocessing is running already.

**Comment by tmcw** [comment]
This is closable, right?

**Comment by DennisOSRM** [comment]
Yes, the duration time thing is tracked in the backend repo
