### ISSUE TITLE
Larger Icons

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-directions.js#37]
I'm finding that the supplied icons are on the small side for navigational purposes. With navigation UI's big, bright direction icons really help the driver/rider/walker quickly understand what is needed next and I'm finding that the turn direction icon is super important to users. It'd be great to have a set of very large icons especially on mobile.

![screen shot 2014-04-16 at 9 34 26 am](https://cloud.githubusercontent.com/assets/1058624/2722196/ff6139d6-c584-11e3-8305-8607c26fc5e9.png)

> Turn icon too small to quickly get gist of next step when going 25mph on a scooter

Perhaps we could do something like `icon-small`, `icon-medium`, `icon-large`

**Comment by bsudekum** [comment]
cc @samanpwbb

**Comment by samanpwbb** [comment]
Base has big icons for directions: https://www.mapbox.com/base/styling/icons/

It's be best to follow those conventions here.

Let me know if you need help porting these over.

**Comment by tmcw** [comment]
Moving discussion to the PR: #38
