### ISSUE TITLE
Remove mapbox.js dep

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-directions.js#40]
Seems like the only hard dependency to mapbox.js is `L.mapbox.marker.icon`: https://github.com/mapbox/mapbox-directions.js/blob/hey-pages/src/layer.js#L14-18 which should be a separate module anyway.

**Comment by jfirebaugh** [comment]
Overall I'm leaning towards keeping the dependency. Previous discussion in #1.

This may hook into v4 API token configuration provided by mapbox.js. I was envisioning something like:

```
    L.mapbox.token = <token>;

    var map = L.mapbox.map('map', 'examples.map-h4cgmpoi')
        .setView([37.77, -122.44], 13);

    var directions = L.mapbox.directions('examples.map-h4cgmpoi');
    var directionsLayer = L.mapbox.directions.layer(directions)
        .addTo(map);
```

And have everything use the one API key.
