### ISSUE TITLE
Remove d3 dep?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-directions.js#43]
- This cuts IE compatibility down to IE10+
- And is about 33% of the total payload at a 29kb dependency

The amount of d3's actual API surface used is pretty minimal - seems like it could be swapped.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
Would prefer to keep. I started out without it but life sucked (there is legit data binding going on here). By my calculation it's ~12% of uncompressed size: 30kb of 262kb.

**Comment by tmcw** [comment]
Okay, as long as this is never included in core, cool w me
