### ISSUE TITLE
Can we support turn by turn directions in other languages?

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-directions.js#45]
cc @DennisOSRM

**Comment by DennisOSRM** [comment]
In principle yes. The backend itself is language agnostic. Certain maneuvers, e.g.. "turn right" are encoded as integers. The [Demo site](http://osrm.at) features 15+ languages in the UI.

@jfirebaugh does the JSON translation for the Mapbox API translate that into text or forward these IDs?

**Comment by jfirebaugh** [comment]
It both forwards the maneuver type (as a string enumeration rather than integer) and provides English text if desired (`instructions` parameter). We'd likely provide i18n support in the backend via a `locale` parameter, so this should be a ticket in api-directions.

**Comment by bsudekum** [comment]
Moving discussion here: https://github.com/mapbox/api-directions/issues/183

**Comment by DennisOSRM** [comment]
thanks @jfirebaugh. What do you think about the following naming convention to avoid confusion?
- backend: OSRM
- middleware: translation from OSRMs output to what the API serves
- frontend: anything that consumes either from above
