### ISSUE TITLE
PSA: upcoming OSRM version is going to announce mode

### ISSUE THREAD

**Issue by DennisOSRM** [mapbox/mapbox-directions.js#47]
We just merged a larger change into OSRM that's going to support mode indication, e.g. it's going to announce when you have take a ferry with the car or perhaps a shuttle train.

The last entry in the instruction array indicate the mode by ID.

``` json
    "route_instructions": [
        [
            "10",
            "Kemberger Straße",
            418,
            0,
            41,
            "418m",
            "SW",
            217,
            1 <--- this guy
        ],...
```

For car directions, we have:
- **1** drive (99.9% of the time)
- **2** ferry
- **3** shuttle train

Up to 16 modes per profile are supported and 15 are available to the user. Mode 0 is used internally to indicate that a (direction of a) road is impassable.

cc: @jfirebaugh

**Comment by kkaefer** [comment]
![screen shot 2014-08-21 at 15 57 58](https://cloud.githubusercontent.com/assets/52399/3997001/3494d468-293b-11e4-9e5b-7139720d7bf3.png)

**Comment by DennisOSRM** [comment]
@kkaefer ?

**Comment by jfirebaugh** [comment]
@DennisOSRM Thanks for the info. So (except for 0), the meanings of the modes are completely determined by the profile, e.g. a cycling profile could have 1 = cyling, 2 = walk your bike, 3 = ferry?

**Comment by DennisOSRM** [comment]
Right, it could be 1 = elephant for that matter.
