### ISSUE TITLE
sprite

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-directions.js#5]
Need a few button icons (marker, reverse) and maneuver icons.
- [x] continue
- [x] bear right
- [x] turn right
- [x] sharp right
- [x] u-turn
- [x] sharp left
- [x] turn left
- [x] bear left
- [x] depart
- [x] enter roundabout
- [x] arrive

**Comment by samanpwbb** [comment]
@jfirebaugh would it make sense to use https://www.mapbox.com/base/styling/icons/ ? I can make whatever is missing from there for you. Figure we'll need these eventually on the mapbox side. (Ignore if this project needs more distance from Mapbox visual style/brand).

**Comment by jfirebaugh** [comment]
Yeah, I started with styles and icons from base. So far the only icons I've used are `marker` and `u-d-arrow` (for "reverse directions", a more specific icon would be better).

We'll need icons for [these maneuvers](https://github.com/mapbox/tilestream-pro/blob/28ccc4abef6e2a337089a2b738f1a2075451de2d/node_modules/mapbox-osrm-transform/src/response.js#L41-L51) and probably more, in the same visual style.

**Comment by samanpwbb** [comment]
fun, I will make these

**Comment by jfirebaugh** [comment]
FYI, in the end I don't think we'll want to hotlink the base assets, or use the same sprite -- Leaflet.directions or mapbox.directions.js, whatever we end up calling it, should stand alone, and should include just the images it needs in the sprite. And it's fine for it to have a Mapbox visual style by default, but it should also be reskinnable.

**Comment by samanpwbb** [comment]
yep, makes sense. If I add them to base can you pull the ones you need?
