### ISSUE TITLE
Multi direction [more 2 marker]

### ISSUE THREAD

**Issue by rajapulau** [mapbox/mapbox-directions.js#53]
it's posible make directions for dynamic marker ?
for example like this
1. Marker A -> Marker B
2. Marker A -> Marker C
3. Marker A -> Marker D
   etc

mapbox great design for map, i like use mapbox for my information. but now, i have some problem wit multi directions

**Comment by jfirebaugh** [comment]
Yes, it is possible to display multiple routes simultaneously by creating multiple instances of `L.mapbox.directions` or `L.mapbox.directions.layer`.

**Comment by MidhunSai** [comment]
Hi @jfirebaugh  can you please provide an example that how can we create multiple directions in one map, for me only one direction is coming the second one is overriding with the first one..
