### ISSUE TITLE
Change function click with manual enter on input

### ISSUE THREAD

**Issue by rajapulau** [mapbox/mapbox-directions.js#54]
how to make Waypoint not using click ... but manual coordinat input and enter.. how i change this function?

**Comment by jfirebaugh** [comment]
With [`directions.addWaypoint`](https://github.com/mapbox/mapbox-directions.js/blob/mb-pages/API.md#directionsaddwaypointindex-waypoint). I've just added this and other waypoint-related functions to API.md.
