### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by tonyspiro** [mapbox/mapbox-directions.js#60]
Getting the error message when trying to set points: "GET https://api.tiles.mapbox.com/v4/directions/mapbox.driving/-74.827880859375,…token=pk.eyJ1IjoiZGFubnl0NDc0IiwiYSI6IlF2UHFxMzgifQ.BFqY_Hcjv-OFeIZl9FHTfw 400 (Bad Request)"

**Comment by tonyspiro** [comment]
I was able to get this to work after downloading the repo.  But this is still an issue if just using the code from https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/

**Comment by jfirebaugh** [comment]
Hi Tony. The Directions API is in preview and requires an account flag to get testing access. I've gone ahead and enabled it on your account.

**Comment by tonyspiro** [comment]
Thanks John!
