### ISSUE TITLE
Please add methods to Readme

### ISSUE THREAD

**Issue by tonyspiro** [mapbox/mapbox-directions.js#61]
I had to search the code to find out how to manually set an origin and destination and run a query.  I think it would help to include this in the Readme:

``` javascript
var directions = L.mapbox.directions();
directions
  .setOrigin(origLng + ',' + origLat)
  .setDestination(destLng + ',' + destLat);
directions.query();
```

**Comment by jfirebaugh** [comment]
We don't want to bloat the README with API documentation, but these are documented in [API.md](https://github.com/mapbox/mapbox-directions.js/blob/mb-pages/API.md).

**Comment by tonyspiro** [comment]
Thanks John!  I didn't see this API file in the repo.  Please point the broken link in the readme to this file.  And thanks for the great plugin!
