### ISSUE TITLE
Document directions.query() in API.md

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-directions.js#62]

**Comment by tmcw** [comment]
Is `query()` the best name for this? It's kind of more general, like `load`

**Comment by jfirebaugh** [comment]
`load`/`loadable` are fine. Better enough to justify a breaking API change? Not sure...

**Comment by tmcw** [comment]
Also fixed in 414f83d0f772f5e79eb334c3b82c36fa068a01e6
