### ISSUE TITLE
limiting your walking directions

### ISSUE THREAD

**Issue by kevinlaanem2gi** [mapbox/mapbox-directions.js#67]
Can you build a limiter for walking direction.I will need a method to limit walking directions to wheelchair="yes" on paths. Little explain "In my case i only need to get directions from these paths where wheelchair="Yes".so if path dont have a property wheelchair="yes" then direction service cant use that path(s)  ". Is this possible to make?

**Comment by TheMarex** [comment]
Sorry that is not possible in at the moment. We hope that we will be able to provide a more flexible routing service at the end of this year.
