### ISSUE TITLE
Use JSDoc?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-directions.js#68]
This would likely let us maintain documentation in a less custom way.

**Comment by jfirebaugh** [comment]
Started sketching this out [here](https://github.com/mapbox/mapbox-directions.js/tree/jsdoc). General impression is that the concepts we want are in jsdoc, but we'd need to make largish investments in dox and/or our own tooling to better support OO libraries.

Related: https://github.com/mapbox/mapbox-gl-js/issues/952
