### ISSUE TITLE
how to handle geocoded origin/destination

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-directions.js#7]
Should `Directions#getOrigin()` return either a `L.LatLng` or a string, depending on whether it's a coordinate or geocoded search? Or should there be separate accessors or something?

After the query is made, should a geocoded string be replaced with the actual coordinate? Or the GeoJSON result of the geocode?

**Comment by tmcw** [comment]
Could be similar to a [LocationEvent](http://leafletjs.com/reference.html#event-objects), like

``` js
{ name: 'foo',
  latLng: L.LatLng
}
```

**Comment by jfirebaugh** [comment]
Going to normalize origin/destination/waypoints to GeoJSON Point Features, which is what the type is in the result JSON. The original query ([lon, lat] or string for geocoding) will be round-tripped in a `query` property of the feature.
