### ISSUE TITLE
setOrigin and setDestination not working

### ISSUE THREAD

**Issue by lukevers** [mapbox/mapbox-directions.js#72]
Hi,

I'm working on a map with a lot of markers that shows the walking directions from a central point when a marker is clicked. At first I wasn't sure how to go about doing this but I saw in issue #65 that @tmcw was doing it this way:

``` javascript
directions.setOrigin([34, -78]);
directions.setDestination([34, -90]);
directions.query();
```

After trying multiple different combinations, I could never get it to work. After looking at the source I saw that both `setOrigin` and `setDestination` call the function `_normalizeWaypoint` to setup the object.

``` javascript
    _normalizeWaypoint: function (waypoint) {
        if (!waypoint || waypoint.type === 'Feature') {
            return waypoint;
        }

        var coordinates,
            properties = {};

        if (waypoint instanceof L.LatLng) {
            waypoint = waypoint.wrap();
            coordinates = properties.query = [waypoint.lng, waypoint.lat];
        } else if (typeof waypoint === 'string') {
            properties.query = waypoint;
        }

        return {
            type: 'Feature',
            geometry: {
                type: 'Point',
                coordinates: coordinates
            },
            properties: properties
        };
    }
```

No format I tried to input in both functions as parameters seemed to actually work. `geometry.coordinates` was always `undefined`. The only way that I could get this to work was by setting the origin and destination explicitly like this:

``` javascript
map.map.featureLayer.on('click', function(e) {
    // First let's get the lat/lng of the marker we just clicked.
    var m_coords = {
        lat: e.layer._latlng.lat,
        lng: e.layer._latlng.lng,
    };

    map.directions.origin = {
        type: 'Feature',
        geometry: {
            coordinates: [map.project.lng, map.project.lat]
        },
        properties: {
            query: [map.project.lng, map.project.lat]
        }
    };

    map.directions.destination = {
        type: 'Feature',
        geometry: {
            coordinates: [m_coords.lng, m_coords.lat]
        },
        properties: {
            query: [m_coords.lng, m_coords.lat]
        }
    };

    map.directions.query();
});
```

(I have everything in a `map` object if you're wondering about `map` prefixing everything). But that works! Here's some screenshots of it working now:

![screen shot 2015-03-02 at 11 52 51 am](https://cloud.githubusercontent.com/assets/1558388/6445554/bb081ee0-c0d2-11e4-864b-5e63ff3b2e79.png)
![screen shot 2015-03-02 at 11 53 02 am](https://cloud.githubusercontent.com/assets/1558388/6445555/bb098b36-c0d2-11e4-9e6e-b6080eee6e7e.png)
![screen shot 2015-03-02 at 11 37 28 am](https://cloud.githubusercontent.com/assets/1558388/6445553/bb079e16-c0d2-11e4-8bd8-caf944d7e9f5.png)

Is there something that I physically did wrong where I was using `setOrigin` and `setDestination` wrong, or is there something wrong with either those two functions or the `_normalizeWaypoint` function?

Another nitpick is that I was confused why `lng` comes before `lat` in the two arrays (`geometry.coordinates` and `properties.query`) when generally `lat` always comes before `lng`.

**Comment by jfirebaugh** [comment]
The code example in #65 is incorrect. `setOrigin` and `setDestination` expect either a L.LatLng object or a GeoJSON Point Feature. For example:

```
directions.setOrigin(L.latLng(34, -78));
```

Most Leaflet click event objects have a latlng member, which you can pass directly to setOrigin/setDestination. For example, see the L.directions.layer click handler: https://github.com/mapbox/mapbox-directions.js/blob/6daf6627f4e748fda02d53920218102e23245a2e/src/layer.js#L95-L103

**Comment by lukevers** [comment]
Awesome, thanks! I don't know how I didn't think to try and pass a `L.latLng` object. I saw another example try `directions.setOrigin(34 + ',' + -78)` somewhere. I think just it's the lack of documentation since the mapbox-directions api is still in beta which had me confused.

**Comment by ejames9** [comment]
Hello, I'm not a JS noob, but I'm still a bit new to classes, so I'm having a bit of a hard time understanding some of the source code. I can setOrigin or setDestination programmatically, by passing in latLng() objects. That being said, I have not been able to figure out how to set waypoints in a similar way. Any help would be appreciated. Thanks!

**Comment by jfirebaugh** [comment]
Is there anything in particular in the [documentation for the waypoint functions](https://github.com/mapbox/mapbox-directions.js/blob/mb-pages/API.md#directionsaddwaypointindex-waypoint) that needs clarification?

**Comment by ejames9** [comment]
Sorry, actually no. I'm a bit embarrassed. I hadn't seen the API.md file, I am a bit new to git hub and open source projects. Anyhow, thank you very much for your quick reply! The documentation is great, and so is the plugin!

**Comment by ejames9** [comment]
Hello again, everything is working great, and I believe that I understand almost everything I need to in order to finish my project. There is however, one small detail that is just bugging the crap out of me. I'm trying everything I can to change the color of the route/path/polyline, but I've yet to figure it out. I'd like to be able to have a different color for each leg. I was hoping it was set up in the options when the new LayerGroup() is instantiated:

var Layer = L.LayerGroup.extend({
    options: {
        readonly: false,
        routeStyle: {
            'color': '#3BB2D0',
            'weight': 4,
            'opacity': 0.75
        }
    },

However, I've played around with this a bit, and nothing changes. I've poured through the API, but to no avail. Obviously I'm doing something wrong, I just haven't figured out what. Any help would be greatly appreciated. I'm so very close to getting where I need to go! Thanks again!

**Comment by lukevers** [comment]
Hey @ejames9,

I'm on this thread because I opened this issue! The docs that @jfirebaugh sent you are nice, but it sounds like you should also checkout the [Leaflet docs](http://leafletjs.com/reference.html) which mapbox is built on!

Anyways, it sounds like you maybe should be using a [Path](http://leafletjs.com/reference.html#path) or a [Polyline](http://leafletjs.com/reference.html#polyline) instead of a LayerGroup if you're trying to draw a line with color.

Also you should checkout both `color` and `fillColor`. The first of the two changes the stroke color, and the second does the fill color.

Not sure if that's what you were looking for, but hopefully this could help you a little bit!

**Comment by jfirebaugh** [comment]
@ejames9 Does https://github.com/mapbox/mapbox-directions.js/issues/84#issuecomment-129995108 help?

**Comment by ejames9** [comment]
@jfirebaugh,

Yes! thank you very much! It's all working great now, I can now change the color for every new directions layer, which is exactly what I was trying to figure out. Thanks again for your help and for responding so quickly! 

@lukevers,

Sorry for hijacking your thread, I'm still getting my bearings here at github. I'll start my own next time:) Thanks anyhow for your help.

**Comment by achalnexus** [comment]
I have draw root line direction using GL-mapbox.
then after i want to remove this root line what i to do.?

   var map = new mapboxgl.Map({
        //hash: true,
        container: 'map',
        style: 'mapbox://styles/achalprajapati/cis1byfch0008hgnitiwbym9c',
        center: [-117.1425, 32.63638889],
        zoom: 6
    });

```
var directions = new mapboxgl.Directions({
    unit: 'metric',
    profile: 'driving',
    container: 'directions',
    proximity: [-117.3186111, 33.10388889]
});


directions.setOrigin([-117.1425, 32.63638889]);
directions.addWaypoint(0, [-117.1425, 32.63638889]);
directions.addWaypoint(1, [-117.195, 32.75416667]);
directions.addWaypoint(2, [-116.5616667, 32.93583333]);
directions.setDestination([-116.5616667, 32.93583333]);

map.addControl(directions);
```
