### ISSUE TITLE
inputControl appears to accept text input

### ISSUE THREAD

**Issue by miccolis** [mapbox/mapbox-directions.js#73]
Not sure if it should accept text input, which get's geocoded, or not but this can be confusing to users. Perhaps users shouldn't be permitted to interact with the context of the text boxes?
For example on https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/ if you immediately enter text into the "A" and "B" text boxes a request is made, but it's incorrectly formatted.

**Comment by tmcw** [comment]
This is a pretty critical bug. Correct behavior would be:
- Geocode address input
- Report failure

**Comment by lbud** [comment]
Fix at https://github.com/mapbox/mapbox-directions.js/pull/74
