### ISSUE TITLE
pinpoint options for routeLayer?

### ISSUE THREAD

**Issue by wyattp11** [mapbox/mapbox-directions.js#84]
Hey guys, trying to set the style for the polyline produced by the routeLayer in directionsLayer... can I use setStyle() on one of these? I've been trying to set an option variable and define the layer like so:

var option = {
readonly:true,
color: "#FFE000",
};

var directionsLayer = L.mapbox.directions.layer(ev_directions, option)
    .addTo(map);

I'm newb, sorry for lame question.

**Comment by jfirebaugh** [comment]
This ability was added in 2f5ee4dd281bd21706ee9c5d087c2c4b8da6f527, but that commit isn't in a released version yet.

The syntax is:

```
L.mapbox.directions.layer(directions, {routeStyle: {color: "#FFE000"}})
  .addTo(map);
```

**Comment by wyattp11** [comment]
Awesome, thank you. That led me to the override in the CSS which works. When do you think next release will be? One check left on that?
