### ISSUE TITLE
Still uses the v3 API

### ISSUE THREAD

**Issue by TheMarex** [mapbox/mapbox-directions.js#85]
The directions API is in version v4 which uses access tokens:

> https://api.mapbox.com/v4/directions/{profile}/{waypoints}.json?access_token=<your access token>

**Comment by jfirebaugh** [comment]
It's v4 here: https://github.com/mapbox/mapbox-directions.js/blob/72e71a83da04e10da941c447156874313f71a358/src/directions.js#L15

Where are you seeing v3 API being used?

**Comment by TheMarex** [comment]
My bad: I was still on `hey-pages` and not `mb-pages` in my local checkout.
