### ISSUE TITLE
Serious issue with 'mapbox.walking' routes on paths designated 'walking only'  

### ISSUE THREAD

**Issue by niborg** [mapbox/mapbox-directions.js#97]
'mapbox.walking' doesn't work on paths designated for foot traffic only.  As far as I've tested, it will work on these paths if bikes are also OK to go on this path.

Example:  Go to latlng 34.0650/-118.5378 -- this is a trail area in Los Angeles, part of which is designated for foot traffic only.  [Link](http://www.openstreetmap.org/edit?pk_campaign=mapbox-edit#map=16/34.0650/-118.5378), may only work if you're logged in.  Here is a picture:
![osm-temescal](https://cloud.githubusercontent.com/assets/11550412/12493136/79683f4a-c038-11e5-9372-243a5048b6d7.png)

Can see clearly marked as foot traffic only.  The path just to the left of the highlighted path is both foot and bike.  Picture:
![screenshot from 2016-01-21 12 23 46](https://cloud.githubusercontent.com/assets/11550412/12493433/d9ee3db4-c039-11e5-80bb-97b16e472f1e.png)

Now try to traverse from left to right onto the footpath only:
![mapbox-directions-temescal](https://cloud.githubusercontent.com/assets/11550412/12493239/049a5b7a-c039-11e5-9803-cd137a776cd4.png)

It stops short of traversing the foot-only path.  To state the obvious, I have tested it in other areas with foot-only paths, and same problem.

(EDIT: somehow took wrong screenshot for one pic)

:

**Comment by jfirebaugh** [comment]
cc @mapbox/directions

**Comment by danpat** [comment]
Looks like we have a configuration problem on our production system; for some users, the `walk` profile is actually returning results from the `bike` profile.

We're correcting the configuration now, and are transparently redirecting all users to a backup server pool that is properly configured.  Requests are now being served as expected:

![screen shot 2016-01-21 at 4 07 36 pm](https://cloud.githubusercontent.com/assets/1892250/12498670/202dda04-c059-11e5-932c-7b94a5275eb8.png)

@niborg thanks for the detailed report, the details made this quick to track down.
